[package]
name = "middleware"
version.workspace = true
authors.workspace = true
repository.workspace = true
edition.workspace = true

[dependencies]
poem = { workspace = true }
chrono = { workspace = true }
tracing = { workspace = true }

helper = { workspace = true }
ty = { workspace = true }
