[package]
name = "payment-gate"
version.workspace = true
authors.workspace = true
repository.workspace = true
edition.workspace = true

[dependencies]
async-stripe = { workspace = true } 
anyhow = { workspace = true }
rand = { workspace = true }
