[package]
name = "crypto"
version.workspace = true
authors.workspace = true
repository.workspace = true
edition.workspace = true

[dependencies]
solana-sdk = { workspace = true }
solana-client = { workspace = true }
anyhow = { workspace = true }
