use std::collections::HashMap;

#[derive(Default)]
pub struct Customer {
    pub name: String,
    pub email: String,
    pub description: String,

    // Address
    pub city: String,
    pub country: String,
    pub addr_line1: String,
    pub addr_line2: String,
    pub postal_code: String,
    pub state: String,

    pub metadata: HashMap<String, String>,
}

pub enum PaymentMethod {
    Card(Card),
}

pub struct Card {
    pub name: String,
    pub number: String,
    pub exp_year: i32,
    pub exp_month: i32,
    pub cvc: String,
}

pub struct CheckoutSession {
    pub id: String,
    pub checkout_url: String,
    /// Generated by us. will return for us in callback
    pub session: String,
}
